
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    user_id: 1,
    post_id:1,
    imgSrc:"https://th.bing.com/th/id/OIP.yTU4CZ3Jovk2d6Vzd-88ZQHaEK?w=277&h=180&c=7&r=0&o=5&dpr=1.6&pid=1.7",
    firstName: "adarsh",
    lastName: "balika",
    username: "adrshikablika",
    password: "adrshika123",
    occupation:"ux designer",
    followers:"400",
    following:"300",
    isFollowing:false,
    ocuLink:"https://google.com",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    user_id: 2,
    post_id:2,
    imgSrc:"https://th.bing.com/th/id/OIP.jNjUF8szRiXc8UxMyEtfxwHaHa?w=170&h=180&c=7&r=0&o=5&dpr=1.6&pid=1.7",
    firstName: "daniel",
    lastName: "shifman",
    username: "danielShifman",
    password: "danielShifman123",
    occupation:"p5js creative thinker",
    followers:"40k",
    following:"300k",
    isFollowing:false,
    ocuLink:"https://google.com",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    user_id: 3,
    post_id:3,
    imgSrc:"https://th.bing.com/th/id/OIP.SsNo1TQldcw0amlglwC1zAHaLJ?w=194&h=292&c=7&r=0&o=5&dpr=1.6&pid=1.7",
    firstName: "aditay",
    lastName: "rajishan",
    username: "aditayraj",
    password: "aditayraj123",
    occupation:"backend engineer",
    followers:"5000",
    following:"300",
    isFollowing:false,
    ocuLink:"https://google.com",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
   user_id: 4,
    post_id:4,
    imgSrc:"https://th.bing.com/th/id/OIP.tUhzmIAKsi_iCzGBvgzF6wAAAA?w=132&h=150&c=7&r=0&o=5&dpr=1.6&pid=1.7",
    firstName: "brad",
    lastName: "traversy",
    username: "bradtraversy",
    password: "traversymedia123",
    isFollowing:false,
    occupation:"coding | Youtuber",
    followers:"4000M",
    following:"30K",
    ocuLink:"https://google.com",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
